blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('post-create', views.post_create, name="post-create"),
    path('post-list', views.post_list, name="post-list"),
    path('post-update/<slug:slug>', views.post_update, name="post-update"),
    path('post-detail/<slug:slug>', views.post_detail, name="post-detail"),
    path('post-remove/<slug:slug>', views.post_remove, name="post-remove"),

]

camp/api/urls.py
from django.urls import path
from camp.api.views import (
    CampListAPIView,
    CampDetailAPIView,
    CampUpdateAPIView,
    CampDeleteAPIView,
    CampCreateAPIView,
    CampCreatePictureAPIView)

urlpatterns = [
    path('camp-list/', CampListAPIView.as_view(), name='api-camp-list'),
    path('camp-detail/<slug>', CampDetailAPIView.as_view(), name='api-camp-detail'),
    path('camp-update/<slug>', CampUpdateAPIView.as_view(), name='api-camp-update'),
    path('camp-delete/<slug>', CampDeleteAPIView.as_view(), name='api-camp-delete'),
    path('camp-create/', CampCreateAPIView.as_view(), name='api-camp-create'),
    path('camp-create-picture/<slug>', CampCreatePictureAPIView.as_view(), name='api-camp-create-picture'),

]

camp/urls.py
from django.urls import path
from camp import views

urlpatterns = [
    path('camp-create', views.camp_create, name="camp-create"),
    path('basic-upload/<slug:slug>', views.upload_photo, name="basic-upload"),
    path('camp-update/<slug:slug>', views.camp_update, name="camp-update"),
    path('camp-detail/<slug:slug>', views.camp_detail, name="camp-detail"),
    path('camp-remove/<slug:slug>', views.camp_remove, name="camp-remove"),
    path('camp-add-or-remove/<slug:slug>', views.add_or_remove_camp, name="camp-add-or-remove"),
    path('new-add-comment/<int:pk>/<str:model_type>', views.new_add_comment, name="new-add-comment"),
    path('get-child-comment-form/', views.get_child_comment_form, name="get-child-comment-form"),
    path('feedback-create/<slug:slug>', views.feedback_create, name="feedback-create"),

]

kamping/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from kamping import settings
from camp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.camp_list, name="camp-list"),
    path('camp/', include('camp.urls')),
    path('auths/', include('auths.urls')),
    path('blog/', include('blog.urls')),

    path('api/camp/', include('camp.api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

camp/models.py
import os
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models

from django.urls import reverse
from django.template.defaultfilters import slugify
from unidecode import unidecode

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from vote.models import VoteModel
from django.shortcuts import get_object_or_404


def upload_to(instance, filename):
    uzanti = filename.split('.')[-1]
    new_name = "%s.%s" % (str(uuid4()), uzanti)
    unique_id = instance.unique_id
    return os.path.join('camp', unique_id, new_name)


class Camp(models.Model):
    CATEGORY = (
        (None, 'Lütfen Seçiniz'), ('diğer', 'DİĞER'), ('yazılım', 'YAZILIM'), ('grafik tasarım', 'GRAFIK TASARIM'))

    STATUS = ((None, 'Lütfen Seçiniz'), ('yayında', 'Yayında'), ('başladı', 'Başladı'), ('bitti', 'Bitti'))

    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yazar", blank=True)
    title = models.CharField(max_length=50, verbose_name="Başlık")
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")
    starter_time = models.TimeField(null=True, verbose_name='Başlangıç saati')

    starter_date = models.DateField(null=True, blank=True,
                                    verbose_name='Başlangıç günü')
    cover_photo = models.CharField(max_length=250, verbose_name='cover_photo', null=True)

    size = models.IntegerField(verbose_name='Katılımcı sayısı', null=True, default=0)
    location = models.CharField(null=True, max_length=255, verbose_name='Lokasyon')
    status = models.CharField(choices=STATUS, default='yayında', blank=True, null=True, max_length=53,
                              verbose_name='Status')

    slug = models.SlugField(null=True, unique=True, editable=False, verbose_name='Slug')
    celery_id = models.CharField(verbose_name='celery_id', null=True, max_length=255)

    def get_absolute_url(self):
        return reverse('camp-detail', kwargs={'slug': self.slug})

    def get_unique_slug(self):
        sayi = 0
        slug = slugify(unidecode(self.title))
        new_slug = slug
        while Camp.objects.filter(slug=new_slug).exists():
            sayi += 1
            new_slug = "%s-%s" % (slug, sayi)
        slug = new_slug
        return slug

    def get_participant_count(self):
        participant_count = self.camp_participants.count()
        return participant_count

    def get_come_camp_object(self):
        data_list = []
        qs = self.camp_participants.all()
        for obj in qs:
            data_list.append(obj.user)
        return data_list

    def get_added_camp_participants_user(self):
        return self.camp_participants.values_list('user__username', flat=True)

    def kalan_katilimci(self):
        katilimci_sayisi = self.get_participant_count()
        return self.size - katilimci_sayisi

    def get_status(self):
        return self.status

    def save(self, *args, **kwargs):
        if self.id is None:
            self.unique_id = str(uuid4())
            self.slug = self.get_unique_slug()
        else:
            camp = Camp.objects.get(slug=self.slug)
            if camp.title != self.title:
                self.slug = self.get_unique_slug()

        super(Camp, self).save(*args, **kwargs)

        return self.title

    def __str__(self):
        return self.title

    def get_camp_new_comment(self):
        content_type = ContentType.objects.get_for_model(self)
        object_id = self.id
        all_comment = Comment.objects.filter(content_type=content_type, object_id=object_id)
        return all_comment

    def get_camp_comment_count(self):
        return len(self.get_camp_new_comment())


class CampParticipants(models.Model):
    user = models.ForeignKey(User, null=True, default=1, related_name='camp_participants', on_delete=models.CASCADE)
    camp = models.ForeignKey(Camp, null=True, on_delete=models.CASCADE, related_name='camp_participants')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi", null=True)

    class Meta:
        verbose_name_plural = 'Kampa gelen katılımcılar'

    def __str__(self):
        return "{} {}".format(self.user, self.camp)


class Photo(models.Model):
    camp = models.ForeignKey(Camp, null=True, on_delete=models.CASCADE, related_name='photo')
    file = models.FileField(upload_to='camp/', default='IMG_4029.JPG', verbose_name='resim', blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.camp)

    def get_image(self):
        if self.file:
            return self.file.url


class Comment(VoteModel, models.Model):
    user = models.ForeignKey(User, null=True, default=1, related_name='+', on_delete=True)
    is_parent = models.BooleanField(default=False)
    content_type = models.ForeignKey(to=ContentType, null=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    icerik = models.TextField(verbose_name='Yorum', max_length=1000, blank=False, null=True)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)

    # camp = models.ForeignKey(Camp, null=True, on_delete=models.CASCADE, related_name='comment')

    def __str__(self):
        username = self.user.username
        text = "{0} {1}".format(username, self.content_type.model)
        return text

    class Meta:
        verbose_name_plural = "Questions"

    @classmethod
    def add_comment(cls, nesne, model_type, user, icerik):
        content_type = ContentType.objects.get_for_model(nesne.__class__)
        cls.objects.create(user=user, icerik=icerik, content_type=content_type, object_id=nesne.pk)
        if model_type == 'comment':
            nesne.is_parent = True
            nesne.save()

    def get_child_comment(self):
        if self.is_parent:
            content_type = ContentType.objects.get_for_model(self.__class__)
            all_child_comment = Comment.objects.filter(content_type=content_type, object_id=self.pk)
            return all_child_comment
        return None


class Feedback(models.Model):
    PUAN = [(None, 'Lütfen birini seçiniz'), (1, '(1) Çok Kötü'), (2, '(2) Kötü'), (3, '(3) Normal'), (4, '(4) İyi'),
            (5, '(5) Çok İyi')]

    user = models.ForeignKey(User, null=True, default=1, related_name='feedback', on_delete=models.CASCADE)
    camp = models.ForeignKey(Camp, null=True, on_delete=models.CASCADE, related_name='feedback')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi", null=True)
    point = models.SmallIntegerField(verbose_name="Puan", choices=PUAN)
    content = models.TextField()

    def __str__(self):
        username = self.user.username
        return "{0} {1}".format(username, self.content)

    @classmethod
    def user_feedback_count(cls, user):
        count = cls.objects.filter(user=user).count()
        return count

camp/forms.py
from django import forms

from camp.models import Camp, Photo, Comment, Feedback


class CampForm(forms.ModelForm):
    starter_date = forms.DateField(input_formats=("%d.%m.%Y",), widget=forms.DateInput(format="%d.%m.%Y"),
                                   required=True,
                                   label="Başlangıç Günü")

    class Meta:
        model = Camp
        fields = ["title", "content", "starter_date", 'starter_time', 'location', 'size']

    def __init__(self, *args, **kwargs):
        super(CampForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': 'form-control', 'id': field}
        DATEPICKER = {
            'type': 'text',
            'class': 'form-control',
            'autocomplete': 'off'
        }

        self.fields['starter_date'].widget.attrs.update(DATEPICKER)


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['icerik']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': 'form-control'}


class SearchForm(forms.Form):
    search = forms.CharField(required=False, max_length=500, widget=forms.TextInput(
        attrs={'placeholder': 'Bir şeyler arayınız ', 'class': 'form-control col-lg-2'}))


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['content', 'point']

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': 'form-control'}

camp/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    CreateAPIView,

    RetrieveUpdateAPIView)

from camp.api.permissions import IsOwner, UserIsVerified
from camp.api.serializers import (
    CampSerializer,
    CampCreateUpdateSerializer,
    CampCreatePictureSerializer
)

from rest_framework.permissions import (
    IsAuthenticated,

    IsAdminUser)

from datetime import datetime, timedelta
from camp.models import Camp, Photo
from camp.tasks import camp_change_status
from kamping.celery import app


class CampListAPIView(ListAPIView):
    queryset = Camp.objects.all()
    serializer_class = CampSerializer


class CampDetailAPIView(RetrieveAPIView):
    queryset = Camp.objects.all()
    serializer_class = CampSerializer
    lookup_field = 'slug'


class CampDeleteAPIView(DestroyAPIView):
    queryset = Camp.objects.all()
    serializer_class = CampSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwner]

    def perform_destroy(self, instance):
        camp = get_object_or_404(Camp, slug=instance.slug)
        app.control.revoke(camp.celery_id)
        instance.delete()


class CampUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Camp.objects.all()
    serializer_class = CampCreateUpdateSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwner]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class CampCreateAPIView(CreateAPIView):
    queryset = Camp.objects.all()
    serializer_class = CampCreateUpdateSerializer
    permission_classes = [IsAuthenticated, UserIsVerified]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)
        camp = get_object_or_404(Camp, title=serializer.data['title'])
        date_time_obj = self.return_data_time_obj(serializer)
        slug = camp.slug
        user = camp.user.username
        res = camp_change_status.apply_async(kwargs={'slug': slug, 'user': user}, eta=date_time_obj)
        camp.celery_id = res.id
        camp.save()

    def return_data_time_obj(self, serializer):
        starter_date = str(serializer.data['starter_date']) + " " + str(serializer.data['starter_time']) + '.0'
        date_time_obj = datetime.strptime(starter_date, '%Y-%m-%d %H:%M:%S.%f')
        date_time_obj = date_time_obj - timedelta(hours=3)
        return date_time_obj


class CampCreatePictureAPIView(CreateAPIView):
    queryset = Photo.objects.all()
    serializer_class = CampCreatePictureSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwner]

    def perform_create(self, serializer):
        camp = get_object_or_404(Camp, slug=self.lookup_field)
        serializer.save(camp=camp)

templates/camp/camp-create.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
    Camp Create
{% endblock %}


{% block ust_icerik %}



    <script type="text/javascript">
        $(function () {
            $('#datetimepicker5').datetimepicker({
                defaultDate: "11/1/2013",
                disabledDates: [
                    moment("12/25/2013"),
                    new Date(2013, 11 - 1, 21),
                    "11/22/2013 00:53"
                ]
            });
        });
    </script>

{% endblock %}
{% block icerik %}


    <div class="camp-create row">
        <div class="col-lg-6 col-lg-offset-3">
            <h1 class="page-header">Camp Create</h1>

            <div class="show-form">
                <form id="step-1-form" action="{% url 'camp-create' %}" enctype="multipart/form-data" method="post">

                    {{ form.media }}
                    {% csrf_token %}

                    {% for field in form %}

                        {% if field.name == 'starter_date' %}

                            <div class="form-group">
                                <label class="control-label">{{ field.label }}</label>
                                <div class='input-group date' id='datetimepicker5'>
                                    <input type='text' class="form-control"/>
                                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                                </div>
                            </div>


                        {% else %}

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <label class="control-label">{{ field.label }}</label>
                                        {{ field }}

                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}

                                        {% else %}
                                            {% if field.help_text %}
                                                <span class="text-success"> {{ field.help_text }}</span>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <input type="submit" value="Kaydet" id="step1"
                                       class=" btn pull-right btn-sm btn-success">
                            </div>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>


{% endblock %}

templates/camp/camp-create_step2.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
    Camp Create
{% endblock %}


{% block ust_icerik %}

    <script src="{% static 'bootstrap/js/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery.fileupload.js' %}"></script>

    <script src="{% static 'js/basic-upload.js' %}"></script>


{% endblock %}
{% block icerik %}

    <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Yükleniyor...</h4>
                </div>
                <div class="modal-body">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="camp-create row">
        <div class="col-lg-6 col-lg-offset-3">
            <h1 class="page-header">Camp Create</h1>

            <div class="show-form">
                <div style="margin-bottom: 20px;">
                    <button type="button" class="js-upload-photos well text-muted text-center"
                            style="padding-top: 4rem; padding-bottom: 4rem;">
                        <span class="glyphicon glyphicon-arrow-down" style="font-size: 4rem;"></span>
                        <h3>Resim yüklemek için sürükleyin veya tıklayın.</h3>
                    </button>
                    <input id="fileupload" type="file" name="file" multiple
                           style="display: none;"
                           data-url="{% url 'basic-upload' slug %}"
                           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

                    <table id="gallery" class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Photo</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for photo in photos %}
                            <div class="col-lg-6">
                                <img class="img-responsive" src="{{ photo.file.url }}" alt="">
                            </div>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>

                <a href="{% url 'camp-list' %}" class="btn btn-info"> Tamamlandı</a>
            </div>
        </div>


{% endblock %}

templates/camp/camp-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ camp.title }}
{% endblock %}


{% block ust_icerik %}
    <style>
        .column img:hover {
            opacity: 1;
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        .container {
            position: relative;
            display: none;
        }

        .closebtn {
            position: absolute;
            top: 10px;
            right: 20px;
            color: white;
            font-size: 35px;
            cursor: pointer;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function () {

            $(".camp-action").on('click', '#add-camp', function (e) {
                e.preventDefault();
                var $this = $(this);
                var $url = $this.attr('href');
                $.ajax({
                    url: $url,
                    method: "GET",
                    data: {},
                    success: function (data) {
                        var response = data.status;
                        var count = data.count;
                        if (data.durum == 'katilamaz') {
                            alert(data.msg);

                        } else {
                            $this.closest('div').find('.camp-participant-count').html(count);
                            if (response == 'added') {
                                $this.closest('ul').find('#add-camp').html("Vazgeç Gönül");

                            } else {
                                $this.closest('ul').find('#add-camp').html("Katıl");

                            }
                        }
                    }
                })
            });

            var $window = $(this);
            var $camp_comment_list = $window.find('#camp-comment-list');
            $window.on('submit', '.comment-form', function (e) {
                e.preventDefault();
                var $this = $(this);
                var $method = $this.attr('method');
                var $data = $this.serialize();
                var $url = $this.attr('action');
                console.log($url);

                $.ajax({

                    url: $url,
                    type: $method,
                    dataType: 'json',
                    data: $data,
                    success: function (data) {
                        console.log(data.camp_comment_html);

                        $camp_comment_list.html(data.camp_comment_html);
                        $this.find('#id_icerik').val('');


                    },
                    error: function () {
                        alert("Bir hata oluştu")
                    }


                })
            });
            $window.on('click', '#camp-comment-list div.row a.yanitla-button', function (e) {
                e.preventDefault();
                var $this = $(this);
                var $parent = $this.closest('div');
                var $href = $this.attr('href');
                var $comment_pk = $this.attr('comment_pk');
                $.ajax({
                    url: $href,
                    type: "GET",
                    dataTyp: "json",
                    data: {'comment_pk': $comment_pk},
                    success: function (data) {
                        console.log(data);
                        var $form_html = data.form_html;
                        $parent.find('.child-form-container').html($form_html);
                    },
                    error: function () {

                    }


                })
            });
        });

        function myFunction(imgs) {
            var expandImg = document.getElementById("expandedImg");

            expandImg.src = imgs.src;

            expandImg.parentElement.style.display = "block";
        }
    </script>

{% endblock %}


{% block icerik %}
    <div class="row">
        <div class="col-lg-12">
            <div id="detail" class="col-lg-7 pull-left">
                <h2><a href="{% url 'camp-list' %}">
                    <span class="glyphicon glyphicon-circle-arrow-left"></span></a> <a>{{ camp.title|upper }}</a>

                </h2>
                <p class="float-left">Etkinlik sahibi: <span
                        class="glyphicon glyphicon-user"></span>
                    <a href="#">{{ camp.user }}</a></p>

                <div class="camp-detail">
                    <div class="cover-photo">
                        <img class="col-lg-12" src="{{ camp.cover_photo }}" alt="" width="100%">
                    </div>
                    <div class="content col-lg-12" style="margin-top: 10px;">
                        <p class="text-capitalize"><span>{{ camp.content | safe }} </span></p>

                    </div>
                </div>

            </div>
            <div class="camp-action col-lg-5 float-left">
                <ul class="list-group list-group-item-text">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-time "></span> Kamp Tarihi:
                        <span>{{ camp.starter_date }} {{ camp.starter_time }}</span>
                    </li>
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-map-marker"></span> Kamp Yeri:<span>{{ camp.location }}</span>
                    </li>
                    <li class="list-group-item">

                        <a id="add-camp" class="btn btn-default btn-block"
                           href="{% url 'camp-add-or-remove' camp.slug %}">
                            {% if request.user.username in camp.get_added_camp_participants_user %}
                                Vazgeç Gönül
                            {% else %}
                                Katıl
                            {% endif %}
                        </a>
                    </li>
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-heart"></span>
                        Katılımcı Sayısı:
                        <span class="camp-participant-count">
                                    <b>{{ camp.get_participant_count }}</b></span>
                    </li>
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-flag"></span>
                        <a class="text-success" href="{{ url }}">Konumu Google haritalarda göster.</a>
                    </li>
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-tag">
                            <a class="text-info" href="{% url 'feedback-create' camp.slug %}">Değerlendir</a>
                        </span>
                    </li>
                </ul>


                <div style="margin-top: 20px;" class="edited">
                    {% if request.user == camp.user %}
                        <ul class="list-group">
                            <li class="list-group-item">
                                <a href="{% url 'camp-update' camp.slug %}" class="text-dark"> <span
                                        class="glyphicon glyphicon-refresh"></span> Gönderiyi Güncelle</a>
                            </li>

                            <li class="list-group-item">
                                <a href="{% url 'camp-remove' camp.slug %}" class=" "> <span
                                        class="glyphicon glyphicon-remove-circle"></span> Gönderiyi Sil</a>

                            </li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="camp-photos col-lg-8 ">
            <h3 class="page-header"><span class="glyphicon glyphicon-picture"></span> Kamp ile ilgili görseller : </h3>

            {% for camp_image in camp_image %}
                <div class="col-lg-2">
                    <div class="column">
                        <img class="float-left" src="{{ camp_image.get_image }}" alt="Nature" height="100px"
                             width="100px"
                             onclick="myFunction(this);">
                    </div>
                </div>
            {% endfor %}

            <div class="container col-lg-12">
                <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>

                <img id="expandedImg" style="width:100%">

                <div id="imgtext"></div>
            </div>


            <div class="pull-center">
                <span class="col-lg-12"><h2 class="page-header">- Sorular - </h2></span>


                <div class="col-lg-12" id="camp-comment-list">

                    <div class="col-lg-10 " id="camp-comment-list">
                        {% include 'camp/include/comment/comment-list-partial.html' with camp=camp %}
                    </div>

                </div>
                <div class="row" style="margin-top: 50px;">

                    <form class="comment-form" action="{% url 'new-add-comment' camp.pk 'camp' %}" method="post">
                        {% csrf_token %}
                        {% for field in comment_form %}
                            <div class="col-lg-1 img-responsive">
                                <img height="60px;" width="60px;"
                                     src="{{ request.user.userprofile.get_profile_photo }}">
                            </div>
                            <div class="col-lg-11">
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <input type="submit" value="Soruyu sor" class="pull-right btn btn-success">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


        </div>

    </div>

{% endblock %}